# Generated by Django 2.0.2 on 2020-03-17 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('billing_name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zipcode', models.IntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('em_uid', models.IntegerField(unique=True, verbose_name='Employee ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('driver', models.BooleanField(default=False)),
                ('helper', models.BooleanField(default=False)),
                ('porter', models.BooleanField(default=False)),
                ('hauler', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('date', models.DateField()),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('sweep', models.NullBooleanField()),
                ('blow', models.NullBooleanField()),
                ('pick', models.NullBooleanField()),
            ],
            options={
                'ordering': ['-job_shift', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('invoice_name', models.CharField(blank=True, max_length=200, null=True)),
                ('property_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('bulk_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('county', models.CharField(blank=True, max_length=30, null=True)),
                ('instructions', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('bi_address', models.CharField(blank=True, max_length=200, null=True)),
                ('bi_city', models.CharField(blank=True, max_length=200, null=True)),
                ('bi_state', models.CharField(blank=True, max_length=200, null=True)),
                ('bi_zipcode', models.IntegerField(blank=True, null=True)),
                ('inv_type', models.CharField(choices=[('SL', 'Single Line'), ('ML', 'Multi Line'), ('MI', 'Multi Invoice'), ('NI', 'No Invoice'), ('RL', 'Repeat Line'), ('Custom', 'Custom')], default='SL', max_length=20)),
                ('inv_date', models.CharField(choices=[('End of Month', 'End of Month'), ('Start of Month', 'Start of Month')], default='End of Month', max_length=50)),
                ('addr1', models.CharField(blank=True, max_length=200, null=True)),
                ('addr2', models.CharField(blank=True, max_length=200, null=True)),
                ('addr3', models.CharField(blank=True, max_length=200, null=True)),
                ('addr4', models.CharField(blank=True, max_length=200, null=True)),
                ('addr5', models.CharField(blank=True, max_length=200, null=True)),
                ('terms', models.CharField(blank=True, max_length=30, null=True)),
                ('saddr1', models.CharField(blank=True, max_length=200, null=True)),
                ('saddr2', models.CharField(blank=True, max_length=200, null=True)),
                ('saddr3', models.CharField(blank=True, max_length=200, null=True)),
                ('saddr4', models.CharField(blank=True, max_length=200, null=True)),
                ('saddr5', models.CharField(blank=True, max_length=200, null=True)),
                ('tosend', models.CharField(default='N', max_length=2)),
                ('update_memo', models.CharField(choices=[('N', 'No'), ('Y', 'Update memo')], default='N', max_length=6)),
                ('memo', models.CharField(blank=True, max_length=200, null=True)),
                ('qty', models.CharField(default='Count', max_length=50)),
                ('rl_qty', models.CharField(default='Count', max_length=50)),
                ('adlspl', models.CharField(blank=True, max_length=500, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('sw_price', models.FloatField(blank=True, null=True)),
                ('sw_mo_price', models.FloatField(blank=True, null=True)),
                ('bu_price', models.FloatField(blank=True, null=True)),
                ('po_price', models.FloatField(blank=True, null=True)),
                ('times_per_week', models.IntegerField(blank=True, null=True)),
                ('days_of_week', models.CharField(blank=True, max_length=7, null=True)),
                ('times_per_month', models.IntegerField(blank=True, null=True)),
                ('times_per_year', models.IntegerField(blank=True, null=True)),
                ('job_costing_report_include', models.BooleanField(default=True)),
                ('check_priority', models.IntegerField(default=1)),
                ('check_interval', models.IntegerField(default=30)),
                ('client_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='work.Client')),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(blank=True, choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday'), ('7', 'Variable')], max_length=20, null=True)),
                ('route_num', models.IntegerField()),
                ('type', models.CharField(default='weekly', max_length=20)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_driver', to='work.Employee')),
            ],
            options={
                'verbose_name_plural': 'routes',
                'ordering': ['weekday', 'route_num'],
            },
        ),
        migrations.CreateModel(
            name='RouteJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('freq', models.CharField(blank=True, max_length=20, null=True)),
                ('job_route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_route', to='work.Route')),
                ('route_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='route_location', to='work.Property')),
            ],
            options={
                'verbose_name_plural': 'route jobs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True, null=True)),
                ('truck', models.IntegerField(blank=True, null=True)),
                ('day_num', models.IntegerField(blank=True, null=True)),
                ('shift_type', models.CharField(blank=True, choices=[('0', 'Sweeping'), ('1', 'Landscaping'), ('2', 'Power Washing'), ('9', 'Other')], default='0', max_length=20, null=True)),
                ('date', models.DateField()),
                ('dr_start_time', models.TimeField(blank=True, null=True, verbose_name='driver start time')),
                ('dr_end_time', models.TimeField(blank=True, null=True, verbose_name='driver end time')),
                ('he_start_time', models.TimeField(blank=True, null=True, verbose_name='helper start time')),
                ('he_end_time', models.TimeField(blank=True, null=True, verbose_name='helper end time')),
                ('he_2_start_time', models.TimeField(blank=True, null=True, verbose_name='second helper start time')),
                ('he_2_end_time', models.TimeField(blank=True, null=True, verbose_name='second helper end time')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sh_driver', to='work.Employee')),
                ('helper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sh_helper', to='work.Employee')),
                ('helper_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sh_helper_2', to='work.Employee')),
            ],
            options={
                'ordering': ['-date', 'day_num'],
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('last_edited', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.IntegerField()),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='shift',
            name='truck_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='truck', to='work.Truck'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location', to='work.Property'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_in_shift', to='work.Shift'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='prop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspection', to='work.Property'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('day_num', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('weekday', 'route_num')},
        ),
    ]
