# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zipcode', models.IntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('em_uid', models.IntegerField(unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('sweep', models.NullBooleanField()),
                ('blow', models.NullBooleanField()),
                ('pick', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('property_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('bulk_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('bi_address', models.CharField(blank=True, max_length=200, null=True)),
                ('bi_city', models.CharField(blank=True, max_length=200, null=True)),
                ('bi_state', models.CharField(blank=True, max_length=200, null=True)),
                ('bi_zipcode', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('sw_price', models.FloatField(blank=True, null=True)),
                ('sw_mo_price', models.FloatField(blank=True, null=True)),
                ('bu_price', models.FloatField(blank=True, null=True)),
                ('po_price', models.FloatField(blank=True, null=True)),
                ('times_per_week', models.IntegerField(blank=True, null=True)),
                ('times_per_month', models.IntegerField(blank=True, null=True)),
                ('times_per_year', models.IntegerField(blank=True, null=True)),
                ('client_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_name', to='work.Client')),
            ],
            options={
                'verbose_name_plural': 'properties',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('truck', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('dr_start_time', models.TimeField(blank=True, null=True, verbose_name='driver start time')),
                ('dr_end_time', models.TimeField(blank=True, null=True, verbose_name='driver end time')),
                ('he_start_time', models.TimeField(blank=True, null=True, verbose_name='helper start time')),
                ('he_end_time', models.TimeField(blank=True, null=True, verbose_name='helper end time')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sh_driver', to='work.Employee')),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sh_helper', to='work.Employee')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='job_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='work.Property'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_in_shift', to='work.Shift'),
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together=set([('driver', 'date')]),
        ),
    ]
