# Generated by Django 2.0.2 on 2018-02-20 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['display_name'], 'verbose_name_plural': 'properties'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='lname',
        ),
        migrations.AddField(
            model_name='employee',
            name='driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='hauler',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='helper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='porter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shift',
            name='last_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='em_uid',
            field=models.IntegerField(unique=True, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location', to='work.Property'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs_in_shift', to='work.Shift'),
        ),
        migrations.AlterField(
            model_name='property',
            name='client_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='work.Client'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sh_driver', to='work.Employee'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='helper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sh_helper', to='work.Employee'),
        ),
    ]
