# Generated by Django 2.0.2 on 2018-05-02 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='inv_type',
            field=models.CharField(choices=[('SL', 'Single Line'), ('ML', 'Multi Line'), ('MI', 'Multi Invoice'), ('NI', 'No Invoice')], default='SL', max_length=2),
        ),
    ]
