# Generated by Django 2.0.2 on 2018-05-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20180501_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rl_qty',
            field=models.CharField(default='Count', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='inv_type',
            field=models.CharField(choices=[('SL', 'Single Line'), ('ML', 'Multi Line'), ('MI', 'Multi Invoice'), ('NI', 'No Invoice'), ('RL', 'Repeat Line'), ('Custom', 'Custom')], default='SL', max_length=2),
        ),
    ]
