# Generated by Django 2.0.2 on 2018-03-10 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20180219_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('prop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='work.Property')),
            ],
            options={
                'ordering': ['date'],
                'verbose_name_plural': '',
            },
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name', '-start_date']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-job_shift']},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['-date', 'driver']},
        ),
    ]
