# Generated by Django 2.0.2 on 2018-03-10 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20180310_1417'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyCheck',
            new_name='Inspection',
        ),
        migrations.AlterModelOptions(
            name='inspection',
            options={'ordering': ['date']},
        ),
    ]
