# Generated by Django 2.0.2 on 2018-05-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20180502_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='inv_type',
            field=models.CharField(choices=[('SL', 'Single Line'), ('ML', 'Multi Line'), ('MI', 'Multi Invoice'), ('NI', 'No Invoice'), ('RL', 'Repeat Line'), ('Custom', 'Custom')], default='SL', max_length=6),
        ),
        migrations.AlterField(
            model_name='property',
            name='update_memo',
            field=models.CharField(choices=[('N', 'No'), ('Y', 'Update memo')], default='N', max_length=6),
        ),
    ]
