# Generated by Django 2.0.2 on 2018-03-10 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_auto_20180310_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='prop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspection', to='work.Property'),
        ),
    ]
