# Generated by Django 2.0.2 on 2018-05-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_auto_20180502_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rl_qty',
            field=models.CharField(default='Count', max_length=50),
        ),
    ]
