# Generated by Django 2.0.2 on 2018-03-11 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_auto_20180311_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='updated',
            field=models.DateTimeField(default='2018-01-01', editable=False),
            preserve_default=False,
        ),
    ]
