# Generated by Django 2.0.2 on 2018-03-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_auto_20180311_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='region',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
