# Generated by Django 2.0.2 on 2018-07-01 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_auto_20180701_0007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routejob',
            options={'ordering': ['order'], 'verbose_name_plural': 'route jobs'},
        ),
        migrations.AlterField(
            model_name='job',
            name='job_shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_in_shift', to='work.Shift'),
        ),
    ]
