# Generated by Django 2.0.2 on 2018-03-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_auto_20180312_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='regular_check',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
