# Generated by Django 2.0.2 on 2018-03-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_property_regular_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='check_interval',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
    ]
