# Generated by Django 2.0.2 on 2018-07-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_auto_20180701_0016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-job_shift', 'order']},
        ),
        migrations.AddField(
            model_name='job',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
