# Generated by Django 2.0.2 on 2018-03-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0011_property_check_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
    ]
