# Generated by Django 2.0.2 on 2018-07-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0011_auto_20180701_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
