# Generated by Django 2.0.2 on 2018-03-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_auto_20180312_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='regular_check',
        ),
        migrations.AddField(
            model_name='property',
            name='check_priority',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
