# Generated by Django 2.0.2 on 2018-10-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_property_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['-date', 'day_num']},
        ),
        migrations.AddField(
            model_name='shift',
            name='day_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('day_num', 'date')},
        ),
    ]
