# Generated by Django 2.0.2 on 2018-03-19 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0013_auto_20180312_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='he_2_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='second helper end time'),
        ),
        migrations.AddField(
            model_name='shift',
            name='he_2_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='second helper start time'),
        ),
        migrations.AddField(
            model_name='shift',
            name='helper_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sh_helper_2', to='work.Employee'),
        ),
    ]
