# Generated by Django 2.0.2 on 2018-03-31 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0015_auto_20180319_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='job_costing_report_include',
            field=models.BooleanField(default=True),
        ),
    ]
