# Generated by Django 2.0.2 on 2018-04-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0017_auto_20180429_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='adlspl',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
