# Generated by Django 2.0.2 on 2018-05-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0018_property_adlspl'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='invoice_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
