# Generated by Django 2.0.2 on 2018-05-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0019_property_invoice_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='qty',
            field=models.CharField(default='Count', max_length=50),
        ),
    ]
