# Generated by Django 2.0.2 on 2018-05-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0020_property_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='billing_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
