# Generated by Django 2.0.2 on 2018-05-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0022_property_inv_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='inv_date',
            field=models.CharField(default='End of Month', max_length=50),
        ),
    ]
