# Generated by Django 2.0.2 on 2018-05-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0023_auto_20180501_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='inv_date',
            field=models.CharField(choices=[('End of Month', 'End of Month'), ('Start of Month', 'Start of Month')], default='End of Month', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='inv_type',
            field=models.CharField(choices=[('SL', 'Single Line'), ('ML', 'Multi Line'), ('MI', 'Multi Invoice')], default='SL', max_length=2),
        ),
    ]
