# Generated by Django 2.0.2 on 2018-05-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0024_auto_20180501_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='update_memo',
            field=models.CharField(choices=[('N', 'No'), ('Y', 'Update memo')], default='N', max_length=2),
        ),
    ]
